import 'dart:convert';

import 'package:flutter_digital_id_platform_interface/flutter_digital_id_platform_interface.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:web/web.dart' as web;

import 'src/web_request_builder.dart' show WebRequestBuilder;

/// Production client implementation of the W3C Digital Credentials API on the web.
///
/// Uses `navigator.credentials.get({ digital: ... })` via `package:web` JS interop.
///
/// The request shape and response extraction heuristics target current drafts
/// of the Digital Credentials API + OpenID4VP (DCQL + mso_mdoc). The client
/// code (builder + extractor + error surface) is complete and hardened.
/// Interoperability ultimately depends on browser + wallet support for the
/// emerging standard.
class FlutterDigitalIdWeb extends DigitalIdPlatform {
  /// Registration entry point.
  ///
  /// Accepts an optional [Registrar] to be compatible with both the modern
  /// `dartPluginClass` mechanism (no-arg) and the registrant generated by
  /// `flutter create --platforms web` / older Flutter web plugin bootstrapping
  /// (which passes a registrar). The parameter is ignored; we only set the
  /// platform instance.
  static void registerWith([Registrar? registrar]) {
    DigitalIdPlatform.instance = FlutterDigitalIdWeb._();
  }

  FlutterDigitalIdWeb._();

  FlutterDigitalIdWeb() : this._();

  @override
  Future<bool> isDigitalIdAvailable(
    DigitalIdType type, {
    DigitalIdRequestOptions? options,
  }) async {
    try {
      // ignore: avoid_dynamic_calls
      final nav = web.window.navigator as dynamic;
      // ignore: avoid_dynamic_calls
      final creds = nav.credentials;
      if (creds == null) return false;

      // Basic presence check for the get() API.
      // A more precise check would look for support of the "digital" option,
      // but that requires actually invoking or deeper capability sniffing.
      // ignore: avoid_dynamic_calls
      return creds.get != null;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<bool> requestPermission(
    DigitalIdType type, {
    DigitalIdRequestOptions? options,
  }) async {
    // On Web the consent prompt is part of the one-shot credentials.get() call.
    // Returning true here indicates "we will request consent at presentation time".
    return true;
  }

  @override
  Future<DigitalIdCredential?> getDigitalId(
    DigitalIdType type, {
    DigitalIdRequestOptions? options,
  }) async {
    try {
      // ignore: avoid_dynamic_calls
      final nav = web.window.navigator as dynamic;
      // ignore: avoid_dynamic_calls
      final creds = nav.credentials;
      if (creds == null) return null;

      final requestJson = WebRequestBuilder.buildRequest(type, options);

      final request = {
        'digital': {
          'requests': [
            {
              'protocol': 'openid4vp',
              'data': jsonDecode(requestJson),
            }
          ]
        }
      };

      // ignore: avoid_dynamic_calls
      final credential = await creds.get(request).toDart as dynamic;
      if (credential == null) return null;

      final extracted = WebRequestBuilder.extractRaw(credential);
      if (extracted == null || extracted.isEmpty) return null;

      return DigitalIdCredential(
        rawCredential: extracted,
        credentialFormat: 'digital-credentials-api',
        metadata: {
          'source': 'web-digital-credentials',
          'protocol': 'openid4vp',
          'optionsUsed': options?.toMap(),
        },
      );
    } catch (e) {
      final msg = e.toString().toLowerCase();
      if (msg.contains('cancel') || msg.contains('abort')) {
        return null; // User cancelled per contract
      }
      // Stronger error surface for non-cancel interop problems (helps debug browser/wallet incompat).
      // Callers should treat non-null returns as success only after backend verification.
      throw DigitalIdException(
        code: DigitalIdErrorCode.requestFailed,
        message: 'Web Digital Credentials request failed: ${e.toString()}',
      );
    }
  }
}
